### ISSUE TITLE
Plugin crashes Domoticz when it is stopped and threads are still active (which is always)

### ISSUE THREAD

**Issue by dnpwwo** [Tsjippy/ChromecastPlugin#18]
Python aborts if an Interpreter is destroyed when threads other than 'MainThread' are active .

This is caused by 2 things:

- Threads in PyChromecast associated with devices are not stopped immediately by Disconnect. Fix is to wait for them to complete using something like:
```
while (threading.active_count() > 1):
        for thread in threading.enumerate():
            if (thread.name != threading.current_thread().name):
                Domoticz.Log("'"+thread.name+"' is still running, waiting otherwise Domoticz will crash on plugin exit.")
        time.sleep(1.0)
``` 

- The fileserver `p = Process(target=server.serve_forever)` function which does what it says.  Recent beta versions of Domoticz natively support HTTP server connections that send binary data so use of http.server.SimpleHTTPRequestHandler is not required. [https://github.com/dnpwwo/Domoticz-Google-Plugin/blob/master/plugin.py](url) has an example of how to do this.  See onNotification, handleMessage and onMessage functions.

**Comment by Tsjippy** [comment]
can you convert this issue to a MR?
