### ISSUE TITLE
Continuous error

### ISSUE THREAD

**Issue by eldigo** [Tsjippy/ChromecastPlugin#48]
I get this error repeatedly in the log
`Error: (ChromeCast) Error on line 802 Error is "name='wp_access_token', domain=None, path=None"`
On lasted Domoticz beta:
Version: 4.11334
Build Hash: 083abdc7e
Compile Date: 2019-09-21 09:14:23
dzVents Version: 2.4.29
Python Version: 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]

running on 
Ubuntu 18.04 server
Any ideas?

**Comment by eldigo** [comment]
Whe I remove the spotify user an password, the error is gone.
Looking at the code.  line 802: `data 					= spotify_token.start_session(self.SpotifyUsername, self.Spotifypassword)`
there seem to an issue with getting the Spotify Token

```
	def GetSpotifyToken(self):
		try:
			if self.SpotifyUsername != "" and self.Spotifypassword != "" and self.SpotifyExpiryTime - time.time() < 60:
				data 					= spotify_token.start_session(self.SpotifyUsername, self.Spotifypassword)
				self.SpotifyAccessToken = data[0]
				self.SpotifyExpiryTime 	= data[1]
				self.SpotifyClient 		= spotipy.Spotify(auth=self.SpotifyAccessToken)
				self.SpotifyUserId 		= self.SpotifyClient.current_user()["id"]
		except requests.exceptions.ConnectionError:
			pass
		except Exception as e:
			senderror(e)
```

**Comment by Tsjippy** [comment]
probably solved with the latest version
